### ISSUE TITLE
Per-world market

### ISSUE THREAD

**Issue by makeevrserg** [Astra-Interactive/AstraAuctions#2]
Example: we have 5 worlds: A,B,C
In world A we can use items from market A,C
In world C we can use items from market worlds A,C
In world B we can use items from market only of world B

Also let's add an ability to block certain worlds from usage of market
```yaml
# This is a first idea of configuration file
blocked_worlds: ["world_d"]
per_world_market:
  world_first:
    name: A
    avaliable_worlds: [ "A", "C"]
  world_second:
    name: C
    avaliable_worlds: [ "A", "C"]
  world_third:
    name: B
    avaliable_worlds: [ "B"]
```
_Author: vdl19#6066_
