### ISSUE TITLE
Add validation to added items

### ISSUE THREAD

**Issue by makeevrserg** [Astra-Interactive/AstraAuctions#4]
Validation config:
For example: items with lore of 2 and more lines can not be added
```yaml
validation:
  lore:
    max_lines: 2
```
